### ISSUE TITLE
getRoutes.tsx: `/`  に対応するページがないため、404と表示されてしまう

### ISSUE THREAD

**Issue by aogumobc** [ih14c-13-14/artist-frontend#19]
`/src/routing/getRoutes.tsx` path `/` に対応するページがない

**Comment by aogumobc** [comment]
なおした
https://github.com/ih14c-13-14/artist-frontend/pull/20

**Comment by na2na-p** [comment]
直ってない

#20のプレビュー環境
https://900c023a.qa-artist.pages.dev/

**Comment by aogumobc** [comment]
拡張子変更の件とごっちゃになってたごめん
なおします
