### ISSUE TITLE
セーフエリア考慮ちゃんとする

### ISSUE THREAD

**Issue by Issiki0416** [ih14c-13-14/artist-frontend#258]
- [ ] 全体的なモバイル対応見たデザイン修正
  - [ ] セーフエリア考慮ちゃんとする

**Comment by Issiki0416** [comment]
セーフエリア参考

https://qiita.com/usagimaru/items/761e9a5f3d78b1939df8

ここで何とかしようとしたけどなんとかなってないのでなんとかしてほしい
https://github.com/ih14c-13-14/artist-frontend/blob/e70ead3c7002005ef098927561714633c6c8cf1f/src/index.scss#L5-L8

**Comment by na2na-p** [comment]
PWAしたときにぶっ壊れてる気もしたけど気のせい
